name: Deploy code to dev env
# new deploy code
on:
  push:  
    branch: 
      - main
      - dev
      - feature/cicd-setup
      - uat
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: |
          echo "Deploying code to the development environment..."
          echo "Deployment successful!"
          echo "send mail to dev team"
          echo "this is new feature""


  
    
